# Generated by Django 4.0.5 on 2022-06-19 20:00

import core.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_informes_chamada_remove_informes_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 293.33, 'width': 360}}, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='palavras',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 293.33, 'width': 360}}, verbose_name='Imagem'),
        ),
    ]
